### ISSUE TITLE
Reduce the number of directories?

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/pallene-tracer#9]
I'm not used to seeing header files in a separate "lib". Can we move them to the "src"?

I also wonder if the ptinit needs to be in it's own directory, and if it could go in the src with everything else.

**Comment by singul4ri7y** [comment]
> I'm not used to seeing header files in a separate "lib". Can we move them to the "src"?

STB headers are generally stored under "lib" directory. I implore you to get used to it.

As for `ptinit`, it can be moved to the 'src' dir.
